version: 0.1

phases:
  install:
    commands:
      - echo Installing dependencies...
      - sudo apt-get update && apt-get -y install apt-transport-https
      - echo Installing Yarn...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get update && sudo apt-get -y install yarn
  pre_build:
    commands:
      - echo Installing NPM dependencies via yarn...
      - yarn install
  build:
    commands:
      - echo Build started
      - yarn build
  post_build:
    commands:
      - echo Build completed, sync to s3 bucket now
      #- aws s3 sync --delete build/ "s3://app.blockkeeper.io"
      #service worker problems
      - aws s3 sync build/ "s3://app.blockkeeper.io"
      #- echo Start Cloudfront invalidation
      #- aws configure set preview.cloudfront true
      #- aws cloudfront create-invalidation --distribution-id E2ML292P0CE01 --paths /*
      - echo Done

artifacts:
  files:
    - build/**/*
